---
sudo: true
language: python
python:
  - '3.8'
services:
  - docker
install:
  - python3 -m pip install molecule[ansible,docker,lint]
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
