---
sudo: true
language: python
services:
  - docker
install:
  - python3 -m pip install yamllint molecule[ansible-base,docker]
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
