---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - python-requests
    - rabbitmq-server

install:
  # Install ansible
  - pip install ansible requests

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ANSIBLE_ROLES_PATH="$PWD"/.. ansible-playbook tests/test.yml -i tests/inventory 

  - tests/verify.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
