---
# EXPECTED VARS:
#
# destination:       required
# destination_type:  required
# bindings:          required a list with zero or more binding objects
#
# A binding object is expected to have the following fields.
# source:       required
# arguments:    optional
# routing_key:  optional
# state:        optional

- name: bind | bind {{ destination_type }} {{ destination }}
  community.rabbitmq.rabbitmq_binding:
    login_port: "{{ rabbitmq_mgmt_port | default(omit) }}"
    login_user: "{{ rabbitmq_admin_user | default(omit) }}"
    login_password: "{{ rabbitmq_admin_password | default(omit) }}"
    vhost: "{{ rabbitmq_vhost_name }}"
    destination: "{{ destination }}"
    destination_type: "{{ destination_type }}"
    name: "{{ item.source }}"
    state: "{{ item.state | default(omit) }}"
    routing_key: "{{ item.routing_key | default(omit) }}"
    arguments: "{{ item.arguments | default(omit) }}"
  no_log: true
  with_items: "{{ bindings }}"
  loop_control:
    label: "{{ item.source }}->{{ destination }}"
