---
# EXPECTED VARS:
#
# exchange:
#   name:         required
#   arguments:    optional
#   auto_delete:  optional
#   bindings:     optional
#   durable:      optional
#   internal:     optional
#   state:        optional
#   type:         optional

- name: Exchange | configure exchange {{ exchange.name }}
  community.rabbitmq.rabbitmq_exchange:
    login_port: "{{ rabbitmq_vhost_mgmt_port | d(omit) }}"
    login_user: "{{ rabbitmq_vhost_admin_user | d(omit) }}"
    login_password: "{{ rabbitmq_vhost_admin_password | d(omit) }}"
    vhost: "{{ rabbitmq_vhost_name }}"
    name: "{{ exchange.name }}"
    state: "{{ exchange.state | d(exchange_default.state) }}"
    auto_delete: "{{ exchange.auto_delete | d(omit) }}"
    durable: "{{ exchange.durable | d(omit) }}"
    exchange_type: "{{ exchange.type | d(omit) }}"
    internal: "{{ exchange.internal | d(omit) }}"
    arguments: "{{ exchange.arguments | d(omit) }}"

- name: Exchange | bind
  when: exchange.state|d(exchange_default.state) == "present"
  ansible.builtin.include_tasks: bind.yml
  vars:
    bindings: "{{ exchange.bindings | d(exchange_default.bindings) }}"
    destination: "{{ exchange.name }}"
    destination_type: exchange
