---
# EXPECTED VARS:
#
# exchange:
#   name:         required
#   arguments:    optional
#   auto_delete:  optional
#   bindings:     optional
#   durable:      optional
#   internal:     optional
#   state:        optional
#   type:         optional

- name: exchange | configure exchange {{ exchange.name }}
  community.rabbitmq.rabbitmq_exchange:
    login_port: "{{ rabbitmq_mgmt_port | default(omit) }}"
    login_user: "{{ rabbitmq_admin_user | default(omit) }}"
    login_password: "{{ rabbitmq_admin_password | default(omit) }}"
    vhost: "{{ rabbitmq_vhost_name }}"
    name: "{{ exchange.name }}"
    state: "{{ exchange.state | default(exchange_default.state) }}"
    auto_delete: "{{ exchange.auto_delete | default(omit) }}"
    durable: "{{ exchange.durable | default(omit) }}"
    exchange_type: "{{ exchange.type | default(omit) }}"
    internal: "{{ exchange.internal | default(omit) }}"
    arguments: "{{ exchange.arguments | default(omit) }}"

- name: exchange | bind
  when: exchange.state|default(exchange_default.state) == "present"
  include_tasks: bind.yml
  vars:
    bindings: "{{ exchange.bindings | default(exchange_default.bindings) }}"
    destination: "{{ exchange.name }}"
    destination_type: exchange
