---
- name: main | Create or remove vhost
  community.rabbitmq.rabbitmq_vhost:
    node: "{{ rabbitmq_node | default(omit) }}"
    name: "{{ rabbitmq_vhost_name }}"
    state: "{{ rabbitmq_vhost_state }}"
    tracing: "{{ rabbitmq_vhost_tracing | default(omit) }}"

- when: rabbitmq_vhost_state == "present"
  block:
    - name: main | configure parameters
      community.rabbitmq.rabbitmq_parameter:
        node: "{{ rabbitmq_node | default(omit) }}"
        vhost: "{{ rabbitmq_vhost_name }}"
        component: "{{ item.component }}"
        name: "{{ item.name }}"
        state: "{{ item.state | default(omit) }}"
        value: "{{ item.value | default(omit) }}"
      with_items: "{{ rabbitmq_vhost_parameters }}"
      loop_control:
        label: "{{ item.name }}"

    - name: main | configure policies
      community.rabbitmq.rabbitmq_policy:
        node: "{{ rabbitmq_node | default(omit) }}"
        vhost: "{{ rabbitmq_vhost_name }}"
        name: "{{ item.name }}"
        state: "{{ item.state | default(policy_default.state) }}"
        pattern: "{{
          item.pattern |
          default(
            policy_default.pattern if item.state|default(policy_default.state) == 'present' else
            omit) }}"
        tags: "{{
          item.tags |
          default(
            policy_default.tags if item.state|default(policy_default.state) == 'present' else
            omit) }}"
        priority: "{{ item.priority | default(omit) }}"
        apply_to: "{{ item.apply_to | default(omit) }}"
      with_items: "{{ rabbitmq_vhost_policies }}"
      loop_control:
        label: "{{ item.name }}"

    - name: main | permissions
      include_tasks: permission.yml
      with_items: "{{ rabbitmq_vhost_users }}"
      loop_control:
        loop_var: user
        label: "{{ user.name }}"

    - name: main | exchanges
      include_tasks: exchange.yml
      with_items: "{{ rabbitmq_vhost_exchanges }}"
      loop_control:
        loop_var: exchange
        label: "{{ exchange.name }}"

    - name: main | queues
      include_tasks: queue.yml
      with_items: "{{ rabbitmq_vhost_queues }}"
      loop_control:
        loop_var: queue
        label: "{{ queue.name }}"
