---
# EXPECTED VARS:
#
# user:
#   name:            required
#   configure_priv:  optional
#   read_priv:       optional
#   write_priv:      optional

- name: permission | retrieve tags for {{ user.name }}
  shell: |
    set -o pipefail
    rabbitmqctl {{ '-n ' ~ rabbitmq_node if rabbitmq_node is defined }} list_users \
      | sed -n 's/^{{ user.name }}[[:space:]]*\[\(.*\)\]$/\1/p'
  register: tag_resp
  changed_when: false

- name: permission | configure permissions for {{ user.name }}
  rabbitmq_user:
    node: "{{ rabbitmq_node | default(omit) }}"
    user: "{{ user.name }}"
    tags: "{{ tag_resp.stdout }}"
    vhost: "{{ rabbitmq_vhost_name }}"
    configure_priv: "{{ user.configure_priv | default(omit) }}"
    read_priv: "{{ user.read_priv | default(omit) }}"
    write_priv: "{{ user.write_priv | default(omit) }}"
