---
# EXPECTED VARS:
#
# queue:
#   name:                     required
#   arguments:                optional
#   auto_delete:              optional
#   auto_expires:             optional
#   bindings:                 optional
#   dead_letter_exchange:     optional
#   dead_letter_routing_key:  optional
#   durable:                  optional
#   max_length:               optional
#   message_ttl:              optional
#   state:                    optional

- name: queue | configure {{ queue.name }}
  community.rabbitmq.rabbitmq_queue:
    login_port: "{{ rabbitmq_mgmt_port | default(omit) }}"
    login_user: "{{ rabbitmq_admin_user | default(omit) }}"
    login_password: "{{ rabbitmq_admin_password | default(omit) }}"
    vhost: "{{ rabbitmq_vhost_name }}"
    name: "{{ queue.name }}"
    state: "{{ queue.state | default(queue_default.state) }}"
    auto_delete: "{{ queue.auto_delete | default(omit) }}"
    auto_expires: "{{ queue.auto_expires | default(omit) }}"
    dead_letter_exchange: "{{ queue.dead_letter_exchange | default(omit) }}"
    dead_letter_routing_key: "{{ queue.dead_letter_routing_key | default(omit) }}"
    durable: "{{ queue.durable | default(omit) }}"
    max_length: "{{ queue.max_length | default(omit) }}"
    message_ttl: "{{ queue.message_ttl | default(omit) }}"
    arguments: "{{ queue.arguments | default(omit) }}"
  no_log: true

- name: queue | bing
  when: queue.state|default(queue_default.state) == "present"
  include_tasks: bind.yml
  vars:
    destination: "{{ queue.name }}"
    destination_type: queue
    bindings: "{{ queue.bindings | default(queue_default.bindings) }}"
