---
- name: Converge
  hosts: all
  collections:
    - ansible.builtin
  tasks:
    - name: create minimal user
      include_role:
        name: ansible-rabbitmq-vhost
      vars:
        rabbitmq_admin_user: admin
        rabbitmq_admin_password: password
        rabbitmq_vhost_name: /vhost1
        rabbitmq_vhost_users:
          - name: user

    - name: create vhost
      include_role:
        name: ansible-rabbitmq-vhost
      vars:
        rabbitmq_admin_user: admin
        rabbitmq_admin_password: password
        rabbitmq_vhost_name: /vhost2
        rabbitmq_vhost_users:
          - name: admin
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        rabbitmq_vhost_exchanges:
          - name: topic-exchange
            type: topic
