---
- name: Converge
  hosts: all
  tasks:
    - name: create minimal user
      include_role:
        name: ansible-rabbitmq-vhost
      vars:
        rabbitmq_vhost_name: /vhost
        rabbitmq_vhost_users:
          - name: user

    - name: create vhost
      include_role:
        name: ansible-rabbitmq-vhost
      vars:
        rabbitmq_admin_user: admin
        rabbitmq_admin_passowrd: password
        rabbitmq_vhost_name: /vhost
        rabbitmq_vhost_users:
          - name: admin
            configure_priv: .*
            read_priv: .*
            write_priv: .*
            
