---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/rabbitmq:management-alpine
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
verifier:
  name: ansible
