---
- name: Prepare
  hosts: all
  collections:
    - ansible.builtin
    - community.rabbitmq
  tasks:
    - name: install requests library
      package:
        name: py3-requests
        state: present

    - name: create user admin
      rabbitmq_user:
        user: admin
        password: password
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator,monitoring

    - name: create user user
      rabbitmq_user:
        name: user
