---
- name: Prepare
  hosts: all
  tasks:
    - name: Install requests library
      ansible.builtin.package:
        name: py3-requests
        state: present

    - name: Create user admin
      community.rabbitmq.rabbitmq_user:
        user: admin
        password: password
        tags: administrator,monitoring
        configure_priv: .*
        read_priv: .*
        write_priv: .*

    - name: Create user user
      community.rabbitmq.rabbitmq_user:
        name: user
