---
- name: Prepare
  hosts: all
  collections:
    - community.rabbitmq
  tasks:
    - name: create user admin
      rabbitmq_user:
        user: admin
        password: password
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator,monitoring

    - name: create user user
      rabbitmq_user:
        name: user
