---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify user user has correct permissions
      ansible.builtin.shell: |
        set -o pipefail
        rabbitmqctl list_permissions --vhost /vhost1 \
          | grep -q -e '^user[[:space:]]\+\^\$[[:space:]]\+\^\$[[:space:]]\+\^\$$'
      changed_when: false

    - name: Verify the vhost /vhost2 created
      ansible.builtin.shell: |
        set -o pipefail
        rabbitmqctl list_vhosts | grep -q -e '^/vhost2$'
      changed_when: false

    - name: Verify user admin has correct permissions
      ansible.builtin.shell: |
        set -o pipefail
        rabbitmqctl list_permissions --vhost /vhost2 \
          | grep -q -e '^admin[[:space:]]\+\.\*[[:space:]]\+\.\*[[:space:]]\+\.\*$'
      changed_when: false

    - name: Verify tags are unchanged
      ansible.builtin.shell: |
        set -o pipefail
        rabbitmqctl list_users \
          | grep -q -e '^admin[[:space:]]\+\[administrator,[[:space:]]*monitoring\]$'
      changed_when: false

    - name: Verify topic-exchange exchange was created
      ansible.builtin.shell: |
        set -o pipefail
        rabbitmqctl list_exchanges --vhost /vhost2 | grep -q -e '^topic-exchange[[:space:]]\+topic$'
      changed_when: false
